---
  - name: Install add-apt-repostory
    package: 
      name: "software-properties-common"
      state: "latest"
    become: yes

  - name: Add Oracle Java Repository
    apt_repository: repo='ppa:webupd8team/java'
    become: yes

  - name: Accept Java 8 License
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    become: yes

  - name: Install Oracle Java 8
    package: 
        name: "{{item}}" 
        state: latest
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
    become: yes